
import { User, Ticket, UserRole, TicketStatus, TicketPriority, TicketCategory } from '../types';

export const mockUsers: User[] = [
  { id: 'u1', name: 'Alice Johnson', role: UserRole.USER, email: 'alice@powergrid.com' },
  { id: 'u2', name: 'Bob Williams', role: UserRole.USER, email: 'bob@powergrid.com' },
  { id: 'a1', name: 'Charlie Brown', role: UserRole.ADMIN, email: 'charlie.admin@powergrid.com' },
  { id: 't1', name: 'David Smith', role: UserRole.TECHNICIAN, email: 'david.tech@powergrid.com' },
  { id: 't2', name: 'Eve Davis', role: UserRole.TECHNICIAN, email: 'eve.tech@powergrid.com' },
];

export const mockTickets: Ticket[] = [
  {
    id: 'TKT-001',
    title: 'Cannot connect to office VPN',
    description: 'My VPN client is showing a connection error. I have tried restarting my machine and the router. This has been happening since this morning. I am on Windows 11.',
    requester: mockUsers[0],
    assignee: mockUsers[3],
    status: TicketStatus.IN_PROGRESS,
    priority: TicketPriority.HIGH,
    category: TicketCategory.NETWORK,
    createdAt: '2023-10-27T10:00:00Z',
    updatedAt: '2023-10-27T11:30:00Z',
    source: 'Web',
    comments: [{ author: 'David Smith', text: 'Checking VPN server logs.', timestamp: '2023-10-27T11:30:00Z' }],
  },
  {
    id: 'TKT-002',
    title: 'Email client not syncing',
    description: 'My Outlook is not receiving new emails. Sending emails seems to work fine. The issue is on my desktop client; mobile is fine.',
    requester: mockUsers[1],
    assignee: mockUsers[4],
    status: TicketStatus.OPEN,
    priority: TicketPriority.MEDIUM,
    category: TicketCategory.SOFTWARE,
    createdAt: '2023-10-27T09:30:00Z',
    updatedAt: '2023-10-27T09:30:00Z',
    source: 'Email',
    comments: [],
  },
  {
    id: 'TKT-003',
    title: 'Request for Adobe Photoshop License',
    description: 'I need a license for Adobe Photoshop for the new marketing project.',
    requester: mockUsers[0],
    assignee: mockUsers[4],
    status: TicketStatus.PENDING,
    priority: TicketPriority.LOW,
    category: TicketCategory.ACCESS,
    createdAt: '2023-10-26T15:00:00Z',
    updatedAt: '2023-10-26T15:00:00Z',
    source: 'GLPI',
    comments: [],
  },
    {
    id: 'TKT-004',
    title: 'Printer on 3rd floor not working',
    description: 'The main printer on the third floor is showing a paper jam error, but there is no paper jammed. It needs to be checked.',
    requester: mockUsers[1],
    assignee: mockUsers[3],
    status: TicketStatus.RESOLVED,
    priority: TicketPriority.MEDIUM,
    category: TicketCategory.HARDWARE,
    createdAt: '2023-10-25T11:00:00Z',
    updatedAt: '2023-10-25T14:00:00Z',
    source: 'Solman',
    comments: [{ author: 'David Smith', text: 'Cleared a hidden sensor jam. The printer is now operational.', timestamp: '2023-10-25T14:00:00Z' }],
  },
  {
    id: 'TKT-005',
    title: 'Password reset for SAP account',
    description: 'I am locked out of my SAP account and need a password reset.',
    requester: mockUsers[0],
    status: TicketStatus.CLOSED,
    priority: TicketPriority.URGENT,
    category: TicketCategory.ACCESS,
    createdAt: '2023-10-27T14:00:00Z',
    updatedAt: '2023-10-27T14:15:00Z',
    source: 'Web',
    comments: [{ author: 'System', text: 'Password reset link sent to user email.', timestamp: '2023-10-27T14:15:00Z' }],
  },
];
